### ISSUE TITLE
最新のhugoではstaticrefが使えない（っぽい）

### ISSUE THREAD

**Issue by Yutaro-Kashiwa** [sdlab-naist/website#129]
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/4554399/166937169-2eed8ec7-eed5-471a-b9cd-7912942fb2e0.png">
おそらく4ファイルほど最新の方法に書き換えないといけない

**Comment by Yutaro-Kashiwa** [comment]
galleryもダメな模様

**Comment by Yutaro-Kashiwa** [comment]
v0.97.1ぐらいから何やら作業している？様子見したほうが良いかもしれない．
https://github.com/gohugoio/hugo/releases

**Comment by Yutaro-Kashiwa** [comment]
新しくHugoを入れる人は，brewをupdateしないようにインストールしたほうがよい（デフォルトでは自動アップデート）
$ HOMEBREW_NO_AUTO_UPDATE=1 brew install hugo

**Comment by Yutaro-Kashiwa** [comment]
staticrefは自作ショートカット？
https://gohugo.io/content-management/shortcodes/

**Comment by keichi** [comment]
staticrefは使用しているテーマ (https://github.com/wowchemy/wowchemy-hugo-themes) で定義されているshortcodeですね．

私もhugo v0.98.0+extendedですが，masterを引っ張ってきてビルド成功するので，hugoのバージョン依存ではない問題だと思います．正確に覚えていないのですが，テーマをうまく引っ張れてきていないときに失敗した気がします．

**Comment by Yutaro-Kashiwa** [comment]
根本原因はわかりませんが，以下のコマンドを打つと治りました
`hugo mod clean`
